FROM golang:1.24.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o blocker-worker ./cmd/blocker_worker

FROM alpine:3.20

# Устанавливаем nftables с retry (для стабильности сборки)
RUN apk --no-cache add nftables || \
    (sleep 5 && apk --no-cache add nftables)

WORKDIR /app

COPY --from=builder /app/blocker-worker .

CMD ["/app/blocker-worker"]