services:
  blocker-xray:
    container_name: blocker-xray
    hostname: blocker-xray
    image: quay.io/fxfuren/remnawave-blocker:0.0.1-dev
    restart: unless-stopped
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '5'
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - remnanode
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'
        reservations:
          memory: 32M
          cpus: '0.10'

  # Ниже "пример" настройки ноды под self steal, но вам главное требуется настроить логирование и vector согласно примеру ниже:
  remnanode:
    container_name: remnanode
    hostname: remnanode
    image: 0fl01/remnawave-node:0.0.1
    restart: unless-stopped
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '5'
    env_file:
      - .env
    volumes:
      - /dev/shm:/dev/shm:rw
      - /var/log/remnanode:/var/log/remnanode # <------- Важный параметр, отсюда обсервер берёт метрики по клиентам

  vector:
    image: timberio/vector:0.48.0-alpine
    container_name: vector
    hostname: vector
    restart: unless-stopped
    network_mode: host
    command: ['--config', '/etc/vector/vector.toml']
    depends_on:
      - remnanode
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - /var/log/remnanode:/var/log/remnanode:ro
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '3'
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.10'
