services:
  observer:
    container_name: observer
    image: quay.io/0fl01/observer-xray-go:0.0.19
    restart: unless-stopped
    expose:
      - '9000'
    volumes:
      - ./data:/app/data:ro # Монтируем директорию с ASN базой
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      vector-aggregator:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: '8m'
        max-file: '3'

  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    container_name: rabbimq-xray
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWD}
    networks:
      - observer-net
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  vector-aggregator:
    image: timberio/vector:0.48.0-alpine
    container_name: vector-aggregator
    restart: unless-stopped
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    expose:
      - '8686'
    command: ['--config', '/etc/vector/vector.toml']
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: '8m'
        max-file: '3'

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '38213:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - vector-aggregator
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: '8m'
        max-file: '3'

  redis:
    image: redis:8.2-m01-alpine3.22
    container_name: redis
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - redis-data:/data
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: '8m'
        max-file: '3'

networks:
  observer-net:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data:
